"""Collects run outputs into EXPERIMENT_REPORT_DATA.md (numbers only; interpretation is written
by hand in EXPERIMENT_REPORT.md)."""
import json

import numpy as np
import pandas as pd

import _path  # noqa: F401
from metrics import macro_f1, paired_bootstrap_diff
from utils import ROOT

RUNS = ROOT / "outputs" / "runs"


def load(run):
    d = RUNS / run
    return json.loads((d / "metrics.json").read_text()) if (d / "metrics.json").exists() else None


def table(df: pd.DataFrame, digits=3) -> str:
    return df.round(digits).to_markdown()


def head_preds(run, query_of):
    p = pd.read_csv(RUNS / run / "predictions.csv")
    out = {}
    for a, g in p.groupby("attribute"):
        g = g[g["query"] == query_of(a)].sort_values("sample_id")
        out[a] = g
    return out


def seed_summary():
    """Key numbers of the USF-MAE pair across seeds 17/29/43 (whatever exists)."""
    rows = []
    for seed in (17, 29, 43):
        sfx = "" if seed == 17 else f"_seed{seed}"
        b, s = load(f"baseline_attributes_usfmae{sfx}"), load(f"clinical_steering_usfmae{sfx}")
        if not (b and s):
            continue
        sim = pd.read_csv(RUNS / f"clinical_steering_usfmae{sfx}" / "representation_similarity.csv")
        attrs = list(s["attributes"])
        pair = sim[sim.rep_a.isin(attrs) & sim.rep_b.isin(attrs) & (sim.rep_a != sim.rep_b)]
        g = pd.read_csv(RUNS / f"clinical_steering_usfmae{sfx}" / "gate_values.csv")
        row = {"seed": seed, "baseline_mean_mF1": b["mean_macro_f1"], "steering_mean_mF1": s["mean_macro_f1"],
               **{f"d_{a}": s["attributes"][a]["macro_f1"] - b["attributes"][a]["macro_f1"] for a in attrs},
               "selectivity_probe": s["selectivity"]["probe_macro_f1"],
               "correct_minus_wrong_mean": float(np.mean([c["correct_query"]["macro_f1"] - c["wrong_query_mean_macro_f1"]
                                                          for c in s["controls"].values()])),
               "min_query_pair_cosine": pair.cosine.min(), "mean_abs_gate": g.gate_tanh_alpha.abs().mean()}
        dj = RUNS / f"diagnosis_comparison{sfx}.json"
        if dj.exists():
            r = json.loads(dj.read_text())["results"]
            for run, key in [("diagnosis_base_usfmae", "auroc_base"), ("diagnosis_clinical_steering", "auroc_steered")]:
                if run in r:
                    row[key + "_logreg"] = r[run]["logreg"]["auroc"]
                    row[key + "_mlp"] = r[run]["mlp"]["auroc"]
        rows.append(row)
    if not rows:
        return []
    df = pd.DataFrame(rows).set_index("seed")
    df.loc["mean"] = df.mean()
    df.loc["sd"] = df.iloc[:-1].std()
    return ["## Seeds (USF-MAE pair)\n", table(df.T), "\n"]


def main():
    lines = ["# Experiment data (auto-generated by scripts/make_report.py)\n"]
    stats = json.loads((ROOT / "outputs/data/dataset_stats.json").read_text())
    lines += ["## Dataset\n", "```json", json.dumps(stats, indent=1), "```\n"]
    eq = ROOT / "outputs/data/equivalence_check.txt"
    if eq.exists():
        lines += ["## Gate = 0 equivalence (real weights)\n", "```", eq.read_text().strip(), "```\n"]
    pairs = [("baseline_attributes_usfmae", "clinical_steering_usfmae"),
             ("baseline_attributes_dinov2", "clinical_steering_dinov2")]
    for base_run, steer_run in pairs:
        b, s = load(base_run), load(steer_run)
        if not (b and s):
            continue
        lines.append(f"## {steer_run} vs {base_run}\n")
        lines.append(f"Parameters: baseline {b['params']}, steering {s['params']}\n")
        rows = {}
        bp = head_preds(base_run, lambda a: "none")
        sp = head_preds(steer_run, lambda a: a)
        dsel = {}
        for a in s["attributes"]:
            gb, gs = bp[a], sp[a]
            keep = gb.attribute_gt.notna().to_numpy()
            y = gb.attribute_gt.to_numpy()[keep]
            lab = {c: i for i, c in enumerate(sorted(set(y) | set(gb.predicted_class) | set(gs.predicted_class)))}
            yi = np.array([lab[v] for v in y])
            pb = np.array([lab[v] for v in gb.predicted_class.to_numpy()[keep]])
            ps = np.array([lab[v] for v in gs.predicted_class.to_numpy()[keep]])
            dsel[a] = paired_bootstrap_diff(macro_f1, yi, pb, ps)
            rows[a] = {"baseline_macro_f1": b["attributes"][a]["macro_f1"],
                       "baseline_ci95": str(np.round(b["attributes"][a]["macro_f1_ci95"], 3)),
                       "steering_macro_f1": s["attributes"][a]["macro_f1"],
                       "steering_ci95": str(np.round(s["attributes"][a]["macro_f1_ci95"], 3)),
                       "diff": dsel[a]["diff"], "diff_ci95": f"[{dsel[a]['ci_low']:.3f}, {dsel[a]['ci_high']:.3f}]",
                       "p": dsel[a]["p_value"],
                       "baseline_bacc": b["attributes"][a]["balanced_acc"],
                       "steering_bacc": s["attributes"][a]["balanced_acc"]}
        lines += ["### Attribute prediction (trained heads, out-of-fold, paired bootstrap)\n",
                  table(pd.DataFrame(rows).T), "\n"]
        lines += ["### Steering selectivity matrix (linear probe macro-F1, rows = query)\n",
                  table(pd.read_csv(RUNS / steer_run / "steering_selectivity_matrix.csv", index_col=0)),
                  f"\nSelectivity: {json.dumps(s['selectivity'])}\n",
                  "### Head-transfer matrix (head_j applied to the query-i embedding)\n",
                  table(pd.read_csv(RUNS / steer_run / "steering_selectivity_matrix_heads.csv", index_col=0)), "\n"]
        ctl = {a: {"correct": c["correct_query"]["macro_f1"], "wrong_mean": c["wrong_query_mean_macro_f1"],
                   "empty": c["empty_query"]["macro_f1"], "generic": c["generic_query"]["macro_f1"],
                   "no_steering_same_heads": c["no_steering_same_heads"]["macro_f1"]}
               for a, c in s["controls"].items()}
        lines += ["### Query controls (trained heads, macro-F1)\n", table(pd.DataFrame(ctl).T), "\n",
                  f"Flags: {s['flags'] or 'none'}\n"]
        sim = pd.read_csv(RUNS / steer_run / "representation_similarity.csv")
        sim = sim[sim.rep_a != sim.rep_b]
        lines += ["### Representation similarity (test folds, mean)\n", sim.round(4).to_markdown(index=False), "\n"]
        g = pd.read_csv(RUNS / steer_run / "gate_values.csv")
        lines += ["### Gates (tanh alpha) and relative update norm, mean over folds\n",
                  table(g.groupby("layer").mean(numeric_only=True).drop(columns="fold"), 4), "\n"]
    dj = RUNS / "diagnosis_comparison.json"
    if dj.exists():
        lines += ["## Diagnosis (benign vs malignant, out-of-fold)\n",
                  table(pd.read_csv(RUNS / "diagnosis_comparison.csv").set_index(["run", "classifier"])),
                  "\n### Paired AUROC differences vs base embedding\n", "```json",
                  json.dumps(json.loads(dj.read_text())["auroc_differences_vs_base"], indent=1), "```\n"]
    lines += seed_summary()
    (ROOT / "EXPERIMENT_REPORT_DATA.md").write_text("\n".join(lines))
    print("\n".join(lines))


if __name__ == "__main__":
    main()
